language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t jhongilp/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jhongilp/docker-react npm run test